site_name: Acceset Docs 


nav:
   - Home: index.md
   - Common Features: common.md
   - Seeker: 'seeker.md'
   - Befriender: 'befriender.md'
   - Moderator: 'moderator.md'
   - Developer: 'developers.md'
   - Admin: admin.md
   


theme: 
    name: material
       